datasets:
  dengue: 
    path: "./data/raw/sample_casos_dengue.txt"
    separator: "|"
    skip_header_lines: 1
    columns: 
      - id
      - data_iniSE
      - casos
      - ibge_code
      - cidade
      - uf
      - cep
      - latitude
      - longitude
  chuvas: 
    path: "./data/raw/sample_chuvas.csv"
    separator: ","
    header: ""
    skip_header_lines: 1
    columns:
      - data
      - mm
      - uf