id: "pipeline_udemy"

dataflow:
  project: "dataflow-397814"
  runner: "DataflowRunner" # SparkRunner (Oracle)
  region: "us-east1"
  staging_location: "gs://acnaweb-datalake/temp"
  temp_location: "gs://acnaweb-datalake/temp"
  template_location: "gs://acnaweb-datalake/template/batch_job_df_gcs_voos"
  save_main_session: True

inputs:
  voos:
    # file: "./data/raw/voos_sample.csv"
    file: "gs://acnaweb-datalake/inputs/voos_sample.csv"
    separator: ","

outputs:
  voos:
    # file: "./data/processed/voos"
    file: "gs://acnaweb-datalake/outputs/voos.csv"        
    header: ""
