job:  
  name: voos-cs-to-cs

use_dataflow: False

gcp:
  project: study-gcp-398200
  temp_location: gs://acnaweb-datalake/temp
  dataflow:
    region: us-west1
    staging_location: gs://acnaweb-datalake/temp
    template_location: gs://acnaweb-datalake/template
    save_main_session: False
    subnetwork: https://www.googleapis.com/compute/v1/projects/dhuodata/regions/us-west1/subnetworks/dhuodata-subnet-stg-cluster
    streaming: False
    max_num_workers: 2
  
dataset:
  input:
    file: gs://acnaweb-datalake/inputs/voos_sample.csv
    separator: ","

  output:
    file: gs://acnaweb-datalake/outputs/voo_enrich.csv
    columns:
    - data
    - col2
    - seq
    - col4
    - col5
    - col6
    - col7
    - col8
    - col9
    - col10
    - col11
    - col12 
    