job:  
  name: pubsub-to-bigtable

gcp:
  project: dhuodata
  dataflow:  
    streaming: True
    max_num_workers: 2
  pubsub:
    topic: projects/dhuodata/topics/input-messages
    subscription: projects/dhuodata/subscriptions/input-messages-sub
                  
  destination:
    instance: "teste-api"
    table: "teste_dry_run"
    key: "row1"
    familia_columns: "input"

dataset:
  input:
    file: gs://dhuoflow-datalake/inputs/voos_sample.csv
    separator: ","
    
  output:
    file: gs://dhuoflow-datalake/outputs/voo_enrich.csv
    table: dhuoflow_dataset.voos
    columns:
    - data
    - col2
    - seq
    - col4
    - col5
    - col6
    - col7
    - col8
    - col9
    - col10
    - col11
    - col12 
    schema:
    - data:STRING
    - col2:INTEGER
    - seq:INTEGER
    - col4:STRING
    - col5:STRING
    - col6:STRING
    - col7:STRING
    - col8:STRING
    - col9:STRING
    - col10:STRING
    - col11:STRING
    - col12:STRING

observability:
  statsDHost: "10.10.0.87"
  # statsDHost: "localhost"
  statsDPort: 9125
  prefix: "statsd_dataflow"