job:  
  name: ingestion-filesystem-to-filesystem
  type: FILE_TO_BIGQUERY
  
pipeline: 
  name: pipelines.steps.to_dict # to_dict | direct_copy | to_list

gcp: 
  project: study-gcp-398200
  temp_location: gs://prefix-datalake-demo/temp
  dataflow: 

dataset:
  input:
    file: gs://prefix-datalake-demo/inputs/voos_sample.csv
    separator: ","
    
  output:
    file: gs://prefix-datalake-demo/outputs/voo_enrich.csv
    table: prefix_dataset_demo.voos
    columns:
    - data
    - col2
    - seq
    - col4
    - col5
    - col6
    - col7
    - col8
    - col9
    - col10
    - col11
    - col12 
    schema:
    - data:STRING
    - col2:INTEGER
    - seq:INTEGER
    - col4:STRING
    - col5:STRING
    - col6:STRING
    - col7:STRING
    - col8:STRING
    - col9:STRING
    - col10:STRING
    - col11:STRING
    - col12:STRING
