job:  
  name: ingestion-filesystem-to-filesystem
  type: FILE_TO_FILE
  
pipeline: 
  name: pipelines.steps.to_dict # to_dict | direct_copy | to_list

gcp:  
  dataflow: None
  
dataset:
  input:
    file: gs://prefix-datalake-demo/inputs/voos_sample.csv
    separator: ","

  output:
    file: gs://prefix-datalake-demo/outputs/voo_enrich.csv
    columns:
    - data
    - col2
    - seq
    - col4
    - col5
    - col6
    - col7
    - col8
    - col9
    - col10
    - col11
    - col12 
    