job:  
  name: dataflow_cs_tocs
  type: FILE_TO_FILE
  
pipeline: 
  name: pipelines.steps.to_list # to_dict | direct_copy | to_list

gcp:
  project: study-gcp-398200
  temp_location: gs://prefix-datalake-demo/temp
  dataflow:
    region: us-west1
    staging_location: gs://prefix-datalake-demo/temp
    template_location: gs://prefix-datalake-demo/template
    save_main_session: True
    subnetwork: https://www.googleapis.com/compute/v1/projects/study-gcp-398200/regions/us-west1/subnetworks/default
    requirements_file: requirements.txt
    streaming: False
    max_num_workers: 2

dataset:
  input:
    file: gs://prefix-datalake-demo/inputs/voos_sample.csv
    separator: ","

  output:
    file: gs://prefix-datalake-demo/outputs/voo_enrich.csv
    columns:
    - data
    - col2
    - seq
    - col4
    - col5
    - col6
    - col7
    - col8
    - col9
    - col10
    - col11
    - col12 
    