job:  
  name: ingestion-filesystem-to-filesystem
  type: FILE_TO_BIGQUERY
  
pipeline: 
  path: /home/ac/Projects/pipelines/
  name: to_dict # to_dict | direct_copy | to_list

gcp:
  project: study-gcp-398200
  temp_location: gs://acnaweb-datalake-demo/temp

dataset:
  input:
    file: gs://acnaweb-datalake-demo/inputs/voos_sample.csv
    separator: ","
    
  output:
    file: gs://acnaweb-datalake-demo/outputs/voo_enrich.csv
    table: acnaweb_dataset_demo.voos
    columns:
    - col1
    - col2
    - col3
    - col4
    - col5
    - col6
    - col7
    - col8
    - col9
    - col10
    - col11
    - col12 
    schema:
    - col1:STRING
    - col2:STRING
    - col3:STRING
    - col4:STRING
    - col5:STRING
    - col6:STRING
    - col7:STRING
    - col8:STRING
    - col9:STRING
    - col10:STRING
    - col11:STRING
    - col12:STRING
