# 1. Anotar o que é constante

gcp:
  project: "dhuodata" 

pubsub:
  topic: "projects/dhuodata/topics/petro-topic-demo"
  subscription: "projects/dhuodata/subscriptions/cloudstorage-sub"

dataflow:
  runner: "DataflowRunner" # default
  region: "us-west1"
  staging_location: "gs://petro-datalake-demo/temp"
  temp_location: "gs://petro-datalake-demo/temp"
  template_location: "gs://petro-datalake-demo/template/stream_to_bigquery"
  save_main_session: True
  subnetwork: "https://www.googleapis.com/compute/v1/projects/dhuodata/regions/us-west1/subnetworks/dhuodata-subnet-stg-cluster"
  requirements_file: "requirements.txt"
  streaming: True
  max_num_workers: 2

input:
  # file: "./data/raw/voos_sample.csv" 
  file: "gs://petro-datalake-demo/inputs/voos_sample.csv"
  separator: ","

output:
  file: 
    name: "gs://petro-datalake-demo/outputs/voo_enrich.csv"        
    columns:
      - col1
      - col2
      - col3
      - col4
      - col5
      - col6
      - col7
      - col8
      - col9
      - col10
      - col11
      - col12 
  bigquery:
    table: "dhuodata:datalake.voos"
    schema: 
      - col1:STRING
      - col2:STRING
      - col3:STRING
      - col4:STRING
      - col5:STRING
      - col6:STRING
      - col7:STRING
      - col8:STRING
      - col9:STRING
      - col10:STRING
      - col11:STRING
      - col12:STRING
