job:
  name: ingestion-filesystem-to-filesystem
  type: FILE_TO_FILE

pipeline: 
  path: /home/ac/Projects/pipelines/
  name: to_dict # to_dict | direct_copy | to_list

dataset:
  input:
    file: ./data/raw/voos_sample.csv
    separator: ","

  output:
    file: ./data/processed/voo_enrich.csv
    columns:
    - col1
    - col2
    - col3
    - col4
    - col5
    - col6
    - col7
    - col8
    - col9
    - col10
    - col11
    - col12 
    