job:
  name: ingestion-filesystem-to-filesystem
  type: FS_FS
  
dataset:
  input:
    file: 
      name: ./data/raw/voos_sample.csv
      separator: ","

  output:
    file: 
      name: ./data/processed/voo_enrich.csv

    