job:
  name: ingestion-filesystem-to-filesystem
  type: FS_FS
  
dataset:
  input:
    file: 
      name: ./data/raw/voos_sample.csv
      separator: ","

  output:
    file: 
      name: ./data/processed/voo_enrich.csv
      columns:
        - col1
        - col2
        - col3
        - col4
        - col5
        - col6
        - col7
        - col8
        - col9
        - col10
        - col11
        - col12 
    