job:  
  name: cs-to-bigquery-dryrun4

use_dataflow: True

gcp:
  project: dhuodata
  temp_location: gs://petrobras-jobs-pubsub/temp
  dataflow:
    region: us-west1
    staging_location: gs://petrobras-jobs-pubsub/template
    template_location: gs://petrobras-jobs-pubsub/template
    save_main_session: False
    subnetwork: https://www.googleapis.com/compute/v1/projects/dhuodata/regions/us-west1/subnetworks/dhuodata-subnet-stg-cluster
    streaming: True
    max_num_workers: 2

dataset:
  input:
    file: gs://petrobras-jobs-pubsub/inputs/voos_sample.csv
    separator: ","
    
  output:
    file: gs://petrobras-jobs-pubsub/outputs/voo_enrich.csv
    table: petro.teste_bigquery
    columns:
    - success
    - datatype
    - timestamp
    - registerId
    - value
    - deviceID
    - tagName
    - deviceName
    - description
    - metadata
    schema:
    - success:STRING
    - datatype:STRING
    - timestamp:STRING
    - registerId:STRING
    - value:STRING
    - deviceID:STRING
    - tagName:STRING
    - deviceName:STRING
    - description:STRING
    - metadata:STRING

    