job:  
  name: pessoas-to-bigtable

use_dataflow: False

gcp:
  project: study-gcp-398200
  temp_location: gs://acnaweb-datalake/temp
  dataflow:
    region: us-west1
    staging_location: gs://acnaweb-datalake/temp
    template_location: gs://acnaweb-datalake/template
    save_main_session: False
    # subnetwork: https://www.googleapis.com/compute/v1/projects/dhuodata/regions/us-west1/subnetworks/dhuodata-subnet-stg-cluster
    subnetwork: https://www.googleapis.com/compute/v1/projects/study-gcp-398200/regions/us-west1/subnetworks/default
    streaming: False
    max_num_workers: 2

dataset:
  input:
    file: /home/ac/Projects/study-apache-beam/data/raw/pessoas.json
    separator: ","
    
  output:
    file: gs://acnaweb-datalake/outputs/pessoas_new.csv
    bigquery: acnaweb_dataset.pessoas
    bigtable: 
      instance: acnaweb-bigtable-instance
      table: pessoas
    columns:
    - data
    - col2
    - seq
    - col4
    - col5
    - col6
    - col7
    - col8
    - col9
    - col10
    - col11
    - col12 
    schema:
    - data:STRING
    - col2:INTEGER
    - seq:INTEGER
    - col4:STRING
    - col5:STRING
    - col6:STRING
    - col7:STRING
    - col8:STRING
    - col9:STRING
    - col10:STRING
    - col11:STRING
    - col12:STRING

    