global:
  scrape_interval:      15s
  evaluation_interval:  15s

scrape_configs:
  # optional: this makes the metrics available to us about Promethus itself.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # tells Prometheus to scrape metrics from exporter at port 9102
  - job_name: 'statsd_metrics'
    static_configs:
      - targets: ['prom-statsd-exporter:9102'] 
        labels: {'host': 'statsd-gcp'}